--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JackMD/MysteryCrate
branches:
- master
projects:
  MysteryCrate:
    path: ""
    icon: meta/MysteryCrate.png
    libs:
      - src: JackMD/UpdateNotifier/UpdateNotifier
        version: ^1.0.0
...
